import { type DayStop, type Connection, WEATHER_DATA, getStartVillage } from "@/lib/plan-engine";

export default function PrintableDayCards({
  stops,
  connections,
  direction,
  month,
}: {
  stops: DayStop[];
  connections: Connection[];
  direction: "north_to_south" | "south_to_north";
  month: number;
}) {
  const weather = WEATHER_DATA[month];

  return (
    <div className="hidden print:block">
      <h1 className="text-2xl font-bold text-primary mb-2 print:text-black">
        Cotswold Way — {stops.length}-Day Itinerary
      </h1>
      <p className="text-sm text-secondary mb-6 print:text-gray-600">
        {direction === "north_to_south" ? "Chipping Campden → Bath" : "Bath → Chipping Campden"}
        {" · "}{weather.month} · {weather.tempLow}–{weather.tempHigh}°C
      </p>

      {stops.map((stop, i) => {
        const from = getStartVillage(stops, i, direction);
        const conn = connections[i];

        // Rest day
        if (stop.restDay) {
          return (
            <div key={stop.day} className="print-card mb-4 border border-blue-200 rounded-lg p-5 bg-blue-50">
              <div className="flex items-center gap-3">
                <span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-blue-200 text-blue-800 font-bold text-sm">
                  {stop.day}
                </span>
                <div>
                  <h2 className="text-lg font-bold text-blue-800">Rest day in {stop.village}</h2>
                  <p className="text-sm text-blue-600">0 miles · Relax and explore the village</p>
                </div>
              </div>
              {stop.note && <p className="text-sm italic text-gray-600 mt-2">{stop.note}</p>}
            </div>
          );
        }

        // Transfer day
        if (stop.transfer) {
          return (
            <div key={stop.day} className="print-card mb-4 border border-gray-200 rounded-lg p-5 bg-gray-50">
              <div className="flex items-center gap-3">
                <span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-gray-300 text-gray-700 font-bold text-sm">
                  {stop.day}
                </span>
                <div>
                  <h2 className="text-lg font-bold text-gray-700">Transfer: {from} → {stop.village}</h2>
                  <p className="text-sm text-gray-500">{stop.miles} miles by bus/taxi</p>
                </div>
              </div>
              {stop.note && <p className="text-sm italic text-gray-600 mt-2">{stop.note}</p>}
            </div>
          );
        }

        // Regular walking day
        return (
          <div key={stop.day} className="print-card mb-4 border border-gray-300 rounded-lg p-5">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-3">
                <span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-gray-900 text-white font-bold text-sm">
                  {stop.day}
                </span>
                <div>
                  <h2 className="text-lg font-bold">{from} → {stop.village}</h2>
                  <p className="text-sm text-gray-600">
                    {stop.miles} miles · {conn?.elevationGain || 0}ft ascent · {conn?.walkTime || "—"}
                  </p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm font-bold">Score {stop.walkScore}/10</p>
                <p className="text-xs text-gray-500 capitalize">{stop.difficulty}</p>
              </div>
            </div>

            <div className="flex gap-4 text-xs text-gray-600">
              <span>Cumulative: {stop.cumulative}mi</span>
              <span>Remaining: {(102 - stop.cumulative).toFixed(1)}mi</span>
              <span>Weather: {weather.tempLow}–{weather.tempHigh}°C</span>
            </div>

            {stop.note && <p className="text-sm italic text-gray-600 mt-2 border-t border-gray-200 pt-2">{stop.note}</p>}
          </div>
        );
      })}

      <p className="text-xs text-gray-400 mt-4">Generated by The Cotswolds Way · thecotswoldsway.com</p>
    </div>
  );
}
